#!/bin/bash

echo_c() {
    local text="$1"
    local color_variable="$2"
    local color="${!color_variable}"
    echo -e "${color}${text}${COLOR_RESET}"
}

get_order() {
  local part_table=$(cgpt show -q "$1")
  local physical_parts=$(awk '{print $1}' <<< "$part_table" | sort -n)
  for part in $physical_parts; do
    grep "^\s*${part}\s" <<< "$part_table" | awk '{print $3}'
  done
}

squash_partitions() {
  for part in $(get_order "$1"); do
    sfdisk -N "$part" --move-data "$1" <<< "+, -" || :
  done
}

truncate_image() {
  local buffer=35
  local sector_size=$(sfdisk -l "$1" 2>/dev/null | grep "^Sector size" | awk '{print $4}')
  local final_sector=$(sfdisk -l -o end "$1" 2>/dev/null | grep "^\s*[0-9]" | awk '{print $1}' | sort -nr | head -n 1)
  local end_bytes=$(((final_sector + buffer) * sector_size))
  if [ -b "$1" ]; then
    local loopdev=$(losetup -f)
    losetup -P "$loopdev" "$1" --sizelimit "$end_bytes"
    sgdisk -e "$loopdev" 2>&1 | sed 's/\a//g'
    losetup -d "$loopdev"
  else
    truncate -s "$end_bytes" "$1"
    sgdisk -e "$1" 2>&1 | sed 's/\a//g'
  fi
  [ -z "$2" ] || echo "$end_bytes" >"$2"
}

debug_msg() {
  if "$verbose"; then
    echo_c $@
  fi
}

verify_syntax() {
    for script in $1; do
        bash -n "$script" || {
            echo_c "Syntax error in $script. Please create an issue at https://github.com/AerialiteLabs/Aurora/issues" RED_B
            exit 1
        }
    done
}

if [ "$EUID" -ne 0 ]; then
    echo "Please run as root."
    exit 1
fi

. rootfs/usr/bin/parse_flags "k,shrimp,krill,0 v,verbose,0 h,help,0 i,!board,image,shim,1 b,!shim,board,1 m,shimsize,1 s,shims,2 r,recovery,2 p,payloads,2" $@ || exit 1

if [ -z "$board" ] && [ -z "$shim" ]; then
    echo "Usage: sudo bash Aurora [-i /path/to/shim.bin]/[-b <board>]"
    exit 1
fi

if [ -z "$board" ] && [ ! -f "$shim" ]; then
  echo_c "File does not exist. Please run on a raw shim." RED_B
  exit 1
fi

if [ -n "$shimsize" ]; then
    sizenum=${shimsize//[!0-9.]/}
    sizeformat=${shimsize//[0-9.]/}
    if ! [[ $sizeformat =~ ^[KMGT]$ ]]; then
        echo_c "--shimsize needs to be formatted in K,M,G,T units." RED_B
        exit 1
    fi
    case $sizeformat in
        K) shimsize=$(echo "(${sizenum})/1" | bc) ;;
        M) shimsize=$(echo "(${sizenum}*1024)/1" | bc) ;;
        G) shimsize=$(echo "(${sizenum}*1024*1024)/1" | bc) ;;
        T) shimsize=$(echo "(${sizenum}*1024*1024*1024)/1" | bc) ;;
    esac
    shimsize
fi

deps=""
for cmd in bc basename cat cgpt chroot chmod cp dd findmnt git grep head losetup mkfs.ext4 mktemp mount mv rm rsync sed sgdisk sync tar touch truncate umount wget; do
    if ! command -v "$cmd" >/dev/null 2>&1; then
        deps+=", $cmd"
    fi
done

if [ -n "$deps" ]; then
    echo "Error: Missing Dependencies: $deps" | sed 's/cies: , /cies: /'
    exit 1
fi

if [ -n "$board" ]; then
    shim="./${board}.bin"
    if [ ! -f "$shim" ]
    then
        wget -q --show-progress "https://github.com/AerialiteLabs/sh1mmer/releases/download/v1.0.0/${board}.bin" -O "$shim" || {
            echo "Invalid board."    
        }
    fi
fi

aurorashim="./aurora-$(basename "$shim")"

temproot=$(mktemp -d)
loopdev=$(losetup -Pf --show $shim)
mount -o ro "${loopdev}p3" "$temproot"

hostarch=$(uname -m)
arch=x86_64
if [ -f "$temproot/bin/bash" ]; then
    case "$(file -b "$temproot/bin/bash" | awk -F ', ' '{print $2}' | tr '[:upper:]' '[:lower:]')" in
        *aarch64* | *armv8* | *arm*) arch=aarch64 ;;
    esac
fi

umount "$temproot"
losetup -d $loopdev
rm -rf "$temproot"