#!/bin/bash

echo_c() {
    local text="$1"
    local color_variable="$2"
    local color="${!color_variable}"
    echo -e "${color}${text}${COLOR_RESET}"
}

debug_msg() {
  if "$verbose"; then
    echo_c $@
  fi
}

lsbval() {
  local key="$1" lsbfile="${2:-$rootfs/etc/lsb-release}"
  echo "$key" | grep -Eq '^[a-zA-Z0-9_]+$' || return 1
  sed -E -n -e "/^[[:space:]]*${key}[[:space:]]*=/{
    s:^[^=]+=[[:space:]]*::
    s:[[:space:]]+$::
    p
  }" "$lsbfile"
}

verify_syntax() {
    for script in $@; do
        bash -n "$script" || { echo_c "Syntax error in $script. Please create an issue at https://github.com/AerialiteLabs/Aurora/issues" RED_B; exit 1; }
    done
}

if [ "$EUID" -ne 0 ]; then
    echo "Please run as root."
    exit 1
fi

. rootfs/usr/bin/parse_flags "q,qemu,0 k,shrimp,krill,0 v,verbose,0 h,help,0 f,firmware,0 i,!board,image,shim,1 b,!shim,board,1 m,shimsize,1 s,shims,2 r,recovery,2 p,payloads,2" $@ || exit 1

if [ -z "$board" ] && [ -z "$shim" ]; then
    echo "Usage: sudo bash Aurora [-i /path/to/shim.bin]/[-b <board>]"
    exit 1
fi

if [ -z "$board" ] && [ ! -f "$shim" ]; then
  echo_c "File does not exist. Please run on a raw shim." RED_B
  exit 1
fi

if [ -n "$shimsize" ]; then
    sizenum=${shimsize//[!0-9.]/}
    sizeformat=${shimsize//[0-9.]/}
    if ! [[ $sizeformat =~ ^[KMGT]$ ]]; then
        echo_c "--shimsize needs to be formatted in K,M,G,T units." RED_B
        exit 1
    fi
    case $sizeformat in
        K) shimsize=$(echo "(${sizenum})/1" | bc) ;;
        M) shimsize=$(echo "(${sizenum}*1024)/1" | bc) ;;
        G) shimsize=$(echo "(${sizenum}*1024*1024)/1" | bc) ;;
        T) shimsize=$(echo "(${sizenum}*1024*1024*1024)/1" | bc) ;;
    esac
    shimsize
fi

deps=""
for cmd in bc basename cat cgpt chroot chmod cp dd findmnt git grep head losetup mkfs.ext4 mktemp mount mv rm rsync sed sgdisk sync tar touch truncate umount wget; do
    if ! command -v "$cmd" >/dev/null 2>&1; then
        deps+=", $cmd"
    fi
done

if [ -n "$deps" ]; then
    echo "Error: Missing Dependencies: $deps" | sed 's/cies: , /cies: /'
    exit 1
fi

if [ -n "$board" ]; then
    shim="./${board}.bin"
    if [ ! -f "$shim" ]
    then
        wget -q --show-progress "https://github.com/AerialiteLabs/sh1mmer/releases/download/v1.0.0/${board}.bin" -O "$shim" || {
            echo "Invalid board."    
        }
    fi
fi

aurorashim="./aurora-$(basename "$shim")"

temproot=$(mktemp -d)
loopdev=$(losetup -Pf --show $shim)
mount -o ro "${loopdev}p3" "$temproot"

hostarch=$(uname -m)
arch=x86_64
if [ -f "$temproot/bin/bash" ]; then
    case "$(file -b "$temproot/bin/bash" | awk -F ', ' '{print $2}' | tr '[:upper:]' '[:lower:]')" in
        *aarch64* | *armv8* | *arm*) arch=aarch64 ;;
    esac
fi
boardname=$(lsbval CHROMEOS_RELEASE_BOARD $temproot/etc/lsb-release)

umount "$temproot"
losetup -d $loopdev
rm -rf "$temproot"