#!/bin/busybox sh

clear

export TTY1="/dev/tty1"
[ -e /dev/pts/0 ] && export TTY1="/dev/pts/0"

/bin/busybox --install /bin || true

dev_partition=$(blkid | grep 'LABEL="Aurora"' | awk -F: '{print $1}' | head -n1 || true)
if [ -z "$dev_partition" ]; then
    echo "failed to find aurora partition"
    sleep 5
    exit 1
fi
bash /resize
sync
mkdir -p /auroraroot

mount $dev_partition /auroraroot || {
    echo "failed to mount aurora partition"
    sleep 5
    exit 1
}

chmod +x /auroraroot/sbin/init /auroraroot/usr/share/aurora/aurora.sh /resize

exec switch_root /auroraroot /sbin/init < "$TTY1" >> "$TTY1" 2>&1