#!/bin/busybox sh

shell() {
  echo "Exited with error code $?. Fallback shell..."
  set +x
  /bin/busybox sh < "$TTY1" >> "$TTY1" 2>&1
  exit 1
}

set -x

[ -e /dev/pts/0 ] && export TTY1="/dev/pts/0" || export TTY1="/dev/tty1"
PATH="/usr/sbin:/usr/bin:/sbin:/bin"
/bin/busybox --install /bin || true

export dev_partition=$(blkid | grep 'LABEL="Aurora"' | awk -F: '{print $1}' | head -n1 || true)

mkdir -p /auroraroot
chmod +x /resize
/resize
shell
mount "$dev_partition" /auroraroot || shell

chmod +x /auroraroot/sbin/init /auroraroot/usr/share/aurora/aurora.sh
mkdir -p /auroraroot/tmp/auroraboot
for dir in dev proc sys; do
  mount -n -o move /$dir /auroraroot/$dir
done
pivot_root /auroraroot /auroraroot/tmp/auroraboot
exec /sbin/init