#!/bin/bash

. /usr/share/aurora/functions

get_partitions

if [ -n "$cros_stateful" ]; then
    mkfs.ext4 -F ${cros_stateful}
    echo_c "Wiped stateful on $cros_drive." GEEN_B | center
else
    fail "No ChromeOS device found"
fi