#!/bin/bash

exec </dev/null >/dev/null 2>&1
pkill -9 frecon || :
rm -rf /run/frecon
mkdir -p /.crosenv/run
mount --bind /run /.crosenv/run
for mnt in /dev /proc /sys; do
    mkdir -p /.crosenv$mnt
    mount --bind "$mnt" "/.crosenv$mnt"
done
chroot /.crosenv frecon-lite --enable-vt1 --daemon --no-login --enable-vts --pre-create-vts --num-vts=8 --enable-gfx
until [ -e /run/frecon/vt0 ]; do
    sleep 0.1
done
exec </run/frecon/vt0 >/run/frecon/vt0 2>&1
disable_input
printf "\033]input:on\a\033]switchvt:0\a"
printf "\033]image:file=/usr/share/aurora/assets/Aurora.png;scale=1\a"