#!/bin/bash
export TERM=xterm-256color
mount --bind /mnt/tmp /mnt/tmp
for mnt in /dev /proc /sys; do
    mount --move $mnt /mnt/tmp$mnt
done
pivot_root /mnt/tmp /mnt/tmp/tmp
pkill -9 frecon || :
rm -rf /run/frecon
frecon-lite --enable-vt1 --daemon --no-login --enable-vts --pre-create-vts --num-vts=8 --enable-gfx
until [ -e /run/frecon/vt0 ]; do
    sleep 0.1
done
exec </run/frecon/vt0 >/run/frecon/vt0 2>&1
stty echo
printf "\033]input:on\a\033]switchvt:0\a"
printf "\033]image:file=/tmp/usr/share/aurora/assets/Aurora.png;scale=1\a"

for mnt in /dev /proc /sys; do
    mount --move $mnt /tmp$mnt
done
pivot_root /mnt/tmp /tmp/mnt/tmp
export TERM=xterm-direct