#!/bin/bash

source /usr/share/aurora/functions
cd /

canwifi apk add mpv yt-dlp
(
    killall frecon-lite
    mpv --vo=drm --volume=100 https://www.youtube.com/watch?v=YQZEoZ4W0ac --slang=en --ytdl-raw-options='ignore-config=,sub-langs="^en.*",write-subs=,write-auto-subs='
)
export TERM=xterm-256color
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
busybox pkill -9 mpv || :
busybox rm -rf /run/frecon
frecon-lite --enable-vt1 --daemon --no-login --enable-vts --pre-create-vts --num-vts=8 --enable-gfx
until [ -e /run/frecon/vt0 ]; do busybox sleep 0.1; done
exec </run/frecon/vt0 >/run/frecon/vt0 2>&1
busybox printf "\033]input:on\a\033]switchvt:0\a"