#!/bin/bash
tput civis
stty -echo
printf "\033]input:on\a"
printf "\033[?25h"
/bin/busybox --install -s /bin
rm -f /init
clear
export TTY1="/dev/tty1"
[ -e /dev/pts/0 ] && export TTY1="/dev/pts/0"
chmod +x /usr/bin/frecon-lite /sbin/startfrecon
startfrecon
setsid -c test
exec bash /usr/share/aurora/aurora.sh