#!/bin/bash

source /usr/share/aurora/functions

busybox pkill -9 frecon || :
busybox rm -rf /run/frecon
frecon-lite --enable-vt1 --daemon --no-login --enable-vts --pre-create-vts --num-vts=8 --enable-gfx
until [ -e /run/frecon/vt0 ]; do busybox sleep 0.1; done
exec </run/frecon/vt0 >/run/frecon/vt0 2>&1
busybox printf "\033]input:on\a\033]switchvt:0\a"