name: Nami

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: github is annoying
      run: |
        git config --global url."https://${{ secrets.SUPERDUPERSECRET }}@github.com/".insteadOf https://github.com/

    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ secrets.SUPERDUPERSECRET }}

    - name: Build Aurora
      run: |
        set -e
        chmod +x fullbuild
        ./fullbuild nami

    - name: Upload built shim
      uses: softprops/action-gh-release@v2
      with:
        name: Aurora ${{ inputs.tag }}
        tag_name: ${{ inputs.tag }}
        files: ./nami-aurora.bin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
